flowey: Restore packages on Windows (#43)
Removing one line enables that, thanks to the people who shipped BSD tar
in-box with Windows, and the people who decided to depend on that in
flowey.

It might look a bit unnecessary at this moment to extract the sysroot
under WIndows yet one day that might help in building OpenHCL IGVM files
on Windows.

The only issue here is that `flowey` tries to delete its working dir and
runs into sharing violations as ProcMon shows:

```
Error: failed to remove directory `R:\src\openvmm\flowey-out\.work`: The process cannot access the file because it is being used by another process. (os error 32)
error: process didn't exit successfully: `target\debug\flowey_hvlite.exe pipeline run restore-packages` (exit code: 0xffffffff)
```

yet the packages are restored properly. Figuring this one out, looking
at the AV settings.