Rename hvlite_entry => openvmm_entry (#297)
Fixes #296 .

```
openvmm> ?
error: unrecognized subcommand '?'

Usage: openvmm <COMMAND>

For more information, try 'help'.
```

I opted to do two things:
1. Update the crate name (because that's the right thing to do), and
2. Explicitly give the REPL prompt a name (`openvmm_entry` doesn't have
the same ring as `openvmm`)